"use server";

import { revalidatePath } from "next/cache";

import { db } from "@/lib/db";
import { projectInWorkspace } from "@/lib/auth/dal";
import { logger } from "@/lib/logger";
import { runAgent } from "@/lib/ai/runtime";
import { metering } from "@/lib/usage/metering";
import { FEATURES } from "@/config/usage";
import { AIError } from "@/lib/ai/errors";
import {
  SECTION_KEYS,
  atlasAgent,
  atlasSectionAgent,
  sectionTitle,
  type StrategyBody,
  type StrategySectionKey,
} from "@/lib/strategy/agent";
import { getStrategy } from "@/lib/strategy/queries";

/**
 * Strategy writes.
 *
 * One rule governs this file: **AI output never overwrites anything**. Every
 * generation and every regeneration appends a new version and moves the current
 * pointer, so a strategy someone has edited by hand cannot be destroyed by
 * pressing a button. Manual edits update the current version in place, because
 * those are deliberate and versioning each keystroke would bury the history
 * that matters.
 */

export interface StrategyResult {
  ok: boolean;
  message?: string;
  versionId?: string;
}

async function ensureStrategy(projectId: string) {
  const existing = await db.strategy.findUnique({ where: { projectId } });
  if (existing) return existing;

  return db.strategy.create({ data: { projectId } });
}

async function nextVersionNumber(strategyId: string) {
  const latest = await db.strategyVersion.findFirst({
    where: { strategyId },
    orderBy: { version: "desc" },
    select: { version: true },
  });

  return (latest?.version ?? 0) + 1;
}

/** Append a version and make it current, in one transaction. */
async function appendVersion(
  strategyId: string,
  note: string,
  body: StrategyBody,
  agentRunId: string | null,
) {
  const version = await nextVersionNumber(strategyId);

  const created = await db.strategyVersion.create({
    data: {
      strategyId,
      version,
      note,
      sections: body.sections as never,
      assumptions: body.assumptions as never,
      missingInformation: body.missingInformation as never,
      agentRunId,
    },
    select: { id: true },
  });

  await db.strategy.update({
    where: { id: strategyId },
    data: { currentVersionId: created.id },
  });

  return created.id;
}

function aiErrorMessage(error: unknown) {
  const retryable = error instanceof AIError ? error.retryable : false;

  return retryable
    ? "The AI provider did not respond. Nothing was changed — try again."
    : "That request could not be completed. Nothing was changed.";
}

export async function generateStrategyAction(
  projectId: string,
  guidance?: string,
): Promise<StrategyResult> {
  const project = await projectInWorkspace(projectId);
  if (!project) return { ok: false, message: "This project no longer exists." };

  const strategy = await ensureStrategy(projectId);
  const isFirst = (await nextVersionNumber(strategy.id)) === 1;

  try {
    const output = await runAgent(atlasAgent, {
      projectId,
      payload: { guidance },
    }, metering(project, FEATURES.strategy));

    const body: StrategyBody = {
      sections: SECTION_KEYS.map((key) => ({
        key,
        content: output.result.sections[key],
        source: "ai" as const,
      })),
      assumptions: output.result.assumptions,
      missingInformation: output.result.missingInformation,
    };

    const versionId = await appendVersion(
      strategy.id,
      isFirst ? "Generated by ATLAS" : "Regenerated by ATLAS",
      body,
      output.runId,
    );

    logger.info("Strategy generated", { projectId, versionId });
    revalidatePath("/strategy");

    return { ok: true, versionId };
  } catch (error) {
    logger.error("Strategy generation failed", {
      projectId,
      message: error instanceof Error ? error.message : String(error),
    });
    return { ok: false, message: aiErrorMessage(error) };
  }
}

/**
 * Rewrite one section. Produces a new version containing the rest of the
 * current strategy unchanged, so an unwanted rewrite is one click to undo.
 */
export async function regenerateSectionAction(
  projectId: string,
  sectionKey: StrategySectionKey,
  guidance?: string,
): Promise<StrategyResult> {
  // Ownership before anything else: `projectId` arrives from the browser.
  const owned = await projectInWorkspace(projectId);
  if (!owned) return { ok: false, message: "This project no longer exists." };

  if (!SECTION_KEYS.includes(sectionKey)) {
    return { ok: false, message: "That is not a strategy section." };
  }

  const strategy = await getStrategy(projectId);
  if (!strategy?.current) return { ok: false, message: "There is no strategy to update yet." };

  const current = strategy.current;

  try {
    const output = await runAgent(atlasSectionAgent, {
      projectId,
      payload: {
        sectionKey,
        guidance,
        currentStrategy: current.body.sections
          .filter((section) => section.key !== sectionKey)
          .map((section) => ({ title: sectionTitle(section.key), content: section.content })),
      },
    }, metering(owned, FEATURES.strategy));

    const body: StrategyBody = {
      sections: current.body.sections.map((section) =>
        section.key === sectionKey
          ? { ...section, content: output.result.content, source: "ai" as const }
          : section,
      ),
      // Assumptions accumulate rather than replace: the ones behind untouched
      // sections still apply.
      assumptions: [...new Set([...current.body.assumptions, ...output.result.assumptions])],
      missingInformation: current.body.missingInformation,
    };

    const versionId = await appendVersion(
      strategy.id,
      `${sectionTitle(sectionKey)} regenerated`,
      body,
      output.runId,
    );

    revalidatePath("/strategy");
    return { ok: true, versionId };
  } catch (error) {
    logger.error("Section regeneration failed", {
      projectId,
      sectionKey,
      message: error instanceof Error ? error.message : String(error),
    });
    return { ok: false, message: aiErrorMessage(error) };
  }
}

/**
 * Save a hand-edited section onto the current version.
 *
 * Updates in place rather than versioning: the operator made this change
 * deliberately, and a version per edit would drown the history of the changes
 * that matter.
 */
export async function editSectionAction(
  projectId: string,
  sectionKey: StrategySectionKey,
  content: string,
): Promise<StrategyResult> {
  // Ownership before anything else: `projectId` arrives from the browser.
  const owned = await projectInWorkspace(projectId);
  if (!owned) return { ok: false, message: "This project no longer exists." };

  const trimmed = content.trim();

  // Checked before the write: an unknown key matched no section, so the update
  // saved the strategy unchanged and still reported success.
  if (!SECTION_KEYS.includes(sectionKey)) {
    return { ok: false, message: "That is not a strategy section." };
  }

  if (!trimmed) return { ok: false, message: "A section cannot be empty." };
  if (trimmed.length > 6000) return { ok: false, message: "That section is too long." };

  const strategy = await getStrategy(projectId);
  if (!strategy?.current) return { ok: false, message: "There is no strategy to edit yet." };

  const sections = strategy.current.body.sections.map((section) =>
    section.key === sectionKey
      ? { ...section, content: trimmed, source: "edited" as const }
      : section,
  );

  await db.strategyVersion.update({
    where: { id: strategy.current.id },
    data: { sections: sections as never },
  });

  revalidatePath("/strategy");
  return { ok: true, versionId: strategy.current.id };
}

/** Make an earlier version current again. The later ones are kept. */
export async function restoreVersionAction(
  projectId: string,
  versionId: string,
): Promise<StrategyResult> {
  // Ownership before anything else: `projectId` arrives from the browser.
  const owned = await projectInWorkspace(projectId);
  if (!owned) return { ok: false, message: "This project no longer exists." };

  const version = await db.strategyVersion.findFirst({
    where: { id: versionId, strategy: { projectId } },
    select: { id: true, strategyId: true, version: true },
  });

  if (!version) return { ok: false, message: "That version does not exist." };

  await db.strategy.update({
    where: { id: version.strategyId },
    data: { currentVersionId: version.id },
  });

  logger.info("Strategy version restored", { projectId, versionId });
  revalidatePath("/strategy");

  return { ok: true, versionId: version.id };
}
