import type { z } from "zod";

/**
 * Core AI types.
 *
 * The provider contract is deliberately narrow: one method, plain data in and
 * out. Anything provider-specific — streaming, tool use, prompt caching — is
 * kept out until a real use case needs it, because a wide interface written
 * against one vendor stops being an abstraction and becomes that vendor's SDK
 * with different names.
 */

export interface AIMessage {
  role: "user" | "assistant";
  content: string;
}

export interface CompletionRequest {
  system: string;
  messages: AIMessage[];
  model: string;
  maxTokens: number;
  temperature: number;
  /** Aborts the in-flight request; the runtime owns the timer. */
  signal?: AbortSignal;
  /**
   * Provider-specific escape hatch. Honoured only by providers that declare
   * support; the mock uses it to script deterministic failure scenarios.
   */
  providerOptions?: Record<string, unknown>;
}

export interface TokenUsage {
  promptTokens: number | null;
  completionTokens: number | null;
}

export interface CompletionResponse {
  text: string;
  usage: TokenUsage;
  /** What the provider actually served, which may differ from what was asked. */
  model: string;
}

export interface AIProvider {
  readonly id: string;
  /** Model used when an agent does not pin one. */
  readonly defaultModel: string;
  complete(request: CompletionRequest): Promise<CompletionResponse>;
}

/* -------------------------------------------------------------------------- */
/* Context                                                                     */
/* -------------------------------------------------------------------------- */

/**
 * Every kind of project data an agent may ask for.
 *
 * Sources with no table in this build are still named here so agents can
 * declare intent now, and the builder reports them as `unavailable` rather than
 * silently returning nothing — an agent should be able to tell the difference
 * between "no campaigns" and "campaigns do not exist yet".
 */
export type ContextSource =
  | "project"
  | "businessProfile"
  | "strategy"
  | "audience"
  | "campaigns"
  | "content"
  | "analytics"
  | "insights"
  | "experimentLearnings"
  | "aiLearning";

export type SliceStatus =
  /** Real data was found and is attached. */
  | "included"
  /** The source exists but holds nothing for this project. */
  | "empty"
  /** No data source exists in this build. */
  | "unavailable";

/**
 * Where a piece of context came from.
 *
 * Carried alongside the data because LUMEN must never let an AI inference
 * harden into a business fact. An agent that cannot tell a stated budget from
 * an inferred one will eventually assert the inference back to the operator as
 * though they had said it.
 */
export type Provenance =
  /** Typed in by the operator. */
  | "user-provided"
  /** From a real file or integration. */
  | "imported"
  /** Generated by a model — a hypothesis, not a fact. */
  | "ai-inferred"
  /** Not currently known. */
  | "unknown";

export interface ContextSlice {
  source: ContextSource;
  status: SliceStatus;
  /** Provenance of everything in `data`. */
  provenance: Provenance;
  data?: unknown;
  /** Explains a non-`included` status in a form safe to put in a prompt. */
  note?: string;
}

export interface AgentContext {
  projectId: string;
  generatedAt: string;
  /** Only the sources the agent asked for. */
  slices: ContextSlice[];
}

/* -------------------------------------------------------------------------- */
/* Agents                                                                      */
/* -------------------------------------------------------------------------- */

export interface AgentInput<TPayload = unknown> {
  projectId: string;
  payload: TPayload;
}

export interface AgentOutput<TResult = unknown> {
  runId: string;
  result: TResult;
  provider: string;
  model: string;
  usage: TokenUsage;
  latencyMs: number;
  attempts: number;
}

/**
 * An agent is a declaration, not a class: what context it needs, what shape it
 * returns, and how to turn an input into a prompt. The runtime owns everything
 * else — retries, timeouts, parsing, persistence — so agents cannot each
 * reinvent their own error handling.
 */
export interface Agent<TPayload, TResult> {
  type: string;
  /** Only these sources are gathered. Asking for less is cheaper and safer. */
  contextSources: ContextSource[];
  /** Validated on every response; a mismatch is a retryable failure. */
  outputSchema: z.ZodType<TResult>;
  system: string;
  buildPrompt(input: AgentInput<TPayload>, context: AgentContext): string;
  /** Short description stored on AgentRun. Must not contain the full prompt. */
  summarizeInput(input: AgentInput<TPayload>): string;
  model?: string;
  maxTokens?: number;
  temperature?: number;
}

export interface StructuredOutput<TResult> {
  result: TResult;
  raw: string;
}
